stages:
  - build
  - lint
  - api
  - security

variables:
  USE_SQLITE: "True"

build-project:
  stage: build
  script:
    - echo "Проверка сборки Django проекта"
    - python3 manage.py check
    - python3 manage.py makemigrations --check --dry-run

lint-project:
  stage: lint
  script:
    - echo "Проверка flake8"
    - flake8 . --output-file=flake8-report.txt
  artifacts:
    paths:
      - flake8-report.txt
    when: always

generate-api-schema:
  stage: api
  script:
    - echo "Генерация OpenAPI схемы"
    - python3 manage.py spectacular --file schema.yml
  artifacts:
    paths:
      - schema.yml
    when: always

security-scan:
  stage: security
  script:
    - echo "Проверка bandit"
    - bandit -r . -f txt -o bandit-report.txt
  artifacts:
    paths:
      - bandit-report.txt
    when: always
