# Generated by Django 5.2.4 on 2025-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_shopproduct_photo_productimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.UniqueConstraint(fields=('shop', 'product', 'material', 'size', 'stones'), name='uniq_shopproduct_variant'),
        ),
    ]
