[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "sGOa7MdDm9KaoYNZ0Z-sxmSG3FpAVZr0dwTUS2741cajp7S_cNWY_6GI8ySUG06RhMLUy-mFOMQAg420H5VEzg=="
  organization = "Cockepinle"
  bucket = "dashboard"

[[inputs.ping]]
  urls = ["yandex.ru"]
  count = 4

[[inputs.http]]
  urls = ["https://api.weatherapi.com/v1/current.json?key=ac89070246734592b68113349250212&q=Moscow&aqi=no"]
  method = "GET"
  data_format = "json"
  json_query = ""
  tag_keys = ["location", "region", "country"]
  [inputs.http.tags]
    source = "weather_moscow"

[[inputs.prometheus]]
  urls = ["http://host.docker.internal:8000/prometheus/metrics"]
  metric_version = 2

