# Generated by Django 5.2.4 on 2025-11-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Администратор'), ('ROLE_MANAGER', 'Менеджер'), ('ROLE_USER', 'Пользователь'), ('ROLE_GUEST', 'Гость')], default='ROLE_USER', max_length=20),
        ),
    ]
