# Generated by Django 5.2.4 on 2025-11-11 19:42

from django.db import migrations, models


def fill_missing_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        email = getattr(user, 'email', '') or ''
        if email.strip() == '':
            user.email = 'user{0}@example.local'.format(user.pk)
            user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.RunPython(fill_missing_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'РђРґРјРёРЅРёСЃС‚СЂР°С‚РѕСЂ'), ('ROLE_MANAGER', 'РњРµРЅРµРґР¶РµСЂ'), ('ROLE_USER', 'РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'), ('ROLE_GUEST', 'Р“РѕСЃС‚СЊ')], default='ROLE_USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'РЎРІРµС‚Р»Р°СЏ'), ('dark', 'РўС‘РјРЅР°СЏ')], default='light', max_length=10),
        ),
    ]
