# Generated by Django 5.2.4 on 2025-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_role_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Администратор'), ('ROLE_MANAGER', 'Менеджер'), ('ROLE_USER', 'Пользователь'), ('ROLE_GUEST', 'Гость')], default='ROLE_USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая тема'), ('dark', 'Тёмная тема')], default='light', max_length=10),
        ),
    ]
