# Generated by Django 5.2.4 on 2025-11-22 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Регламент резервного копирования',
                'verbose_name_plural': 'Регламент резервного копирования',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
